---
- name: assert mandatory variables have been set
  assert:
    that:
    - domain_setup__network_name is defined
    - domain_setup__domain_name is defined
    - domain_setup__safe_mode_password is defined
    - domain_setup__username is defined
    - domain_setup__password is defined

- name: set the DNS for the specified adapter to localhost
  win_dns_client:
    adapter_name: '{{ domain_setup__network_name }}'
    ipv4_addresses: 127.0.0.1

- name: ensure domain exists and DC is promoted as a domain controller
  win_domain:
    dns_domain_name: '{{ domain_setup__domain_name }}'
    safe_mode_password: '{{ domain_setup__safe_mode_password }}'
  register: domain_setup__register_install

- name: reboot DC if required after install
  win_reboot:
  when: domain_setup__register_install.reboot_required

- name: create domain username
  win_domain_user:
    name: '{{ domain_setup__username }}'
    upn: '{{ domain_setup__username }}@{{ domain_setup__domain_name }}'
    description: '{{ domain_setup__username }} Domain Account'
    password: '{{ domain_setup__password }}'
    password_never_expires: yes
    groups:
    - Domain Admins
    state: present
  register: domain_setup__register_create_user
  # after reboot, the netlogon service isn't available immediately, we need
  # to retry until this succeeeds
  retries: 30
  delay: 15
  until: domain_setup__register_create_user is successful

- name: test out domain user that was created
  win_whoami:
  become: yes
  become_method: runas
  vars:
    ansible_become_user: '{{ domain_setup__username }}@{{ domain_setup__domain_name }}'
    ansible_become_pass: '{{ domain_setup__password }}'
